jobs:
  default:
    runs-on: "cpu=4/ram=16/family=m7a+m7i-flex/image=ubuntu22-full-x64"
    steps:
      - name: Display NVIDIA SMI details
        run: |
          nvidia-smi
          nvidia-smi -L
          nvidia-smi -q -d Memory
      - name: Ensure Docker is available with GPU support
        run: docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
      - name: Execute your machine learning script
        run: echo "Running ML script..."
